[build]
  command = "yarn build"
  publish = "dist"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "*.(css|ico|png|svg)"
  [headers.values]
    Cache-Control = "immutable,max-age=31536000"
[[headers]]
  for = "src.*.js"
  [headers.values]
    Cache-Control = "immutable,max-age=31536000"
[[redirects]]
  from = "api/*"
  status = 200
  to = "https://nkw6whtyg5.execute-api.us-east-1.amazonaws.com/prod/:splat"
[[redirects]]
  from = "*"
  status = 200
  to = "/"
