[build]
  command = "npm run build"
  publish = "dist"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none';report-uri https://o4504114345017344.ingest.sentry.io/api/4504114369527808/security/?sentry_key=7fc7812ff3d6482ba2113d6fc90177fa"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "*.(avif|css|md|png|svg|woff2)"
  [headers.values]
    Cache-Control = "immutable,max-age=31536000"
[[headers]]
  for = "index.*.js"
  [headers.values]
    Cache-Control = "immutable,max-age=31536000"
[[redirects]]
  from = "api/*"
  status = 200
  to = "https://nkw6whtyg5.execute-api.us-east-1.amazonaws.com/prod/:splat"
[[redirects]]
  from = "*"
  status = 200
  to = "/"
