export default (() => {
  const keys = [
    "addMoodRadioButton",
    "dateAwokeInput",
    "deviceSetupDialog",
    "eventAddPage",
    "eventAddSubmitButton",
    "eventCardDateTime",
    "eventCardValue",
    "explorationInput",
    "hoursSleptInput",
    "legRaisesValueInput",
    "meditatePage",
    "meditationCustomTimeInput",
    "meditationPresetTimeButton",
    "meditationTimerPage",
    "minutesSleptInput",
    "moodCardMood",
    "moodCardTags",
    "moodCardTime",
    "moodList",
    "navButton",
    "pushUpsValueInput",
    "resetPasswordPage",
    "runCardDistance",
    "runCardTime",
    "runMetersInput",
    "runMinutesInput",
    "runNoInputErrorMessage",
    "runSecondsInput",
    "signInLink",
    "signOutButton",
    "signOutConfirmButton",
    "sitUpsValueInput",
    "sleepCardValue",
    "statsOverviewPage",
    "weightValueInput",
  ] as const;
  const testIds = {} as Record<(typeof keys)[number], (typeof keys)[number]>;
  for (const key of keys) testIds[key] = key;
  return testIds;
})();
